<section id="home">

    <?php
        $this->partialLoop()->setObjectKey('project');
        echo $this->partialLoop('partials/homeproject.phtml', $this->projects);
    ?>

</section>

<a href="#portfolio" class="link_arrow arrow_down link_portfolio"></a>

<section id="portfolio">
        <div id="stage">
        <?php
            $this->partialLoop()->setObjectKey('project');
            echo $this->partialLoop('partials/project.phtml', $this->projects);
        ?>
    </div>
    <h1 id="portfoliotitle">Portfolio</h1>
    <nav id="projectlisting">
        <ul>
        <?php
            $this->partialLoop()->setObjectKey('project');
            echo $this->partialLoop('partials/projectnav.phtml', $this->projects);
        ?>
        </ul>
    </nav>


</section>

<a href="#about" class="link_arrow arrow_down link_about"></a>

<section id="about">

    <h1>Over mij</h1>
    <p>Mijn passie voor het maken van kleding ontstond rond mijn twaalfde, de beginselen leerde ik van mijn oma die coupeuse was.
        De liefde voor theater kwam aan het einde van de middelbare school om de hoek kijken toen ik de kostuums voor een film van een vriendin verzorgde.
        Na het propedeusejaar aan de Kunstacademie in Maastricht koos ik voor Theaterkostuumontwerp en verplaatste ik naar Toneelacademie in Maastricht.
        Sinds het begin van die opleiding heb ik voor leuke en mooie projecten de kostuums kunnen ontwerpen.
        Ik hou van de theaterwereld, de manier waarop je samen met regisseur en acteurs een project induikt en alles geeft om er een mooie voorstelling van te maken.
        Daarnaast heb ik een grote liefde voor het maken van de kleding zelf. Momenteel studeer ik verder aan de Meesteropleiding Coupeur om mijn technische kennis uit te breiden.</p>
</section>

<a href="#contact" class="link_arrow arrow_down link_contact"></a>

