<div name="Home" class="sausage-page-selector">
<section id="home">

    <?php
        $this->partialLoop()->setObjectKey('project');
        echo $this->partialLoop('partials/homeproject.phtml', $this->projects);
    ?>

</section>

<a href="#portfolio" class="link_arrow arrow_down link_portfolio"></a>

</div><!-- End of HOME sausage page selector -->

<div name="Portfolio" class="sausage-page-selector">

<section id="portfolio">
        <div id="stage">
        <?php
            $this->partialLoop()->setObjectKey('project');
            echo $this->partialLoop('partials/project.phtml', $this->projects);
        ?>
    </div>
    <h1 id="portfoliotitle">Portfolio</h1>
    <nav id="projectlisting">
        <ul>
        <?php
            $this->partialLoop()->setObjectKey('project');
            echo $this->partialLoop('partials/projectnav.phtml', $this->projects);
        ?>
        </ul>
    </nav>


</section>

<a href="#about" class="link_arrow arrow_down link_about"></a>

</div>

<div name="Over mij" class="sausage-page-selector">

<section id="about">

    <h1>Over mij</h1>
    <p>Mijn passie voor het maken van kleding  ontstond rond mijn twaalfde, de beginselen leerde ik van mijn oma die coupeuse  was.
        De liefde voor theater kwam aan het einde van de middelbare school toen ik  de kostuums voor een film van een vriendin verzorgde.
        Na het propedeusejaar aan  de Kunstacademie in Maastricht koos ik voor Theaterkostuumontwerp en  verplaatste ik naar Toneelacademie in Maastricht.
        Sinds het begin van die  opleiding heb ik voor leuke en mooie projecten de kostuums kunnen ontwerpen.
        Ik  heb een grote liefde voor het theater, de manier waarop je samen met regisseur en acteurs een project induikt
        en alles geeft om er een mooie voorstelling van  te maken.</p>
    <p>Naast het ontwerpen en theater interesseer ik  mij erg voor het vakwerk wat ten grondslag ligt aan het maken van kleding.
        Daarom  ben ik in augustus 2011 begonnen aan de Meesteropleiding Coupeur. Op de  opleiding kan ik in drie jaar mijn technische kennis uitbreiden tot op het
        hoogste niveau. Naast de opleiding ben ik zo veel mogelijk aan het werk in de  vakgebieden die mij interesseren; mode, theater, coupeurswerk en ontwerpen.</p>
</section>

<a href="#contact" class="link_arrow arrow_down link_contact"></a>

</div>
