<article class="project" id="art_pid_<?=$this->project->getId()?>">
    <h1><?= $this->project->getTitle() ?></h1>
    <h2><?= $this->project->getSubtitle() ?></h2>
    <?= $this->project->getContent()?>
    <div class="lightbox">
        <?php

            if ($imgs = $this->project->getImgs()) {

                foreach($imgs as $img) {
                    echo '<a class="photo_thumb" rel="prettyPhoto[' . $this->project->getName() . ']" href="' . $img['big'] . '"><img src="' . $img['thumb'] . '" alt="" width="75" height="69"></a>';


                }

            }

        ?>
    </div>
</article>